# Generated by Django 3.1.7 on 2021-04-09 23:29

import administracion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('ruc', 'RUC')], default='cedula', max_length=10)),
                ('numero_documento', models.CharField(max_length=13)),
                ('direccion', models.TextField(max_length=200)),
                ('telefono_casa', models.CharField(max_length=10)),
                ('telefono_celular', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres y apellidos')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono de contacto')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo  Electrónico')),
                ('consulta', models.TextField(blank=True, null=True, verbose_name='Ingrese su consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombrep', models.CharField(max_length=100, verbose_name='Nombre de Producto')),
                ('marcap', models.CharField(max_length=100, verbose_name='Marca de Producto')),
                ('descripcionp', models.TextField(verbose_name='Descripción de Producto')),
                ('valor', models.FloatField(verbose_name='Valor de Producto')),
                ('imagenproducto', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Permisos',
                'verbose_name_plural': 'Gestionar Roles',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('color', models.CharField(max_length=50, verbose_name='Color de Vehiculo')),
                ('kilometraje', models.IntegerField(verbose_name='Kilometraje')),
                ('observaciones', models.TextField(verbose_name='Descripción del problema')),
                ('fechaIngreso', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('numero_factura', models.CharField(blank=True, default=administracion.models.incremento_numero_factura, max_length=20, null=True, verbose_name='Número de factura')),
                ('subtotal', models.FloatField()),
                ('descuento', models.FloatField()),
                ('iva', models.FloatField()),
                ('valor_final', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
                ('producto_detalle', models.ManyToManyField(to='administracion.ProductoDetalle')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('ruc', 'RUC')], default='cedula', max_length=10)),
                ('numero_documento', models.CharField(max_length=13)),
                ('direccion', models.TextField(max_length=200)),
                ('telefono_casa', models.CharField(max_length=10)),
                ('telefono_celular', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Gestionar Empleados',
                'ordering': ['apellidos'],
            },
        ),
    ]
