# Generated by Django 3.1.7 on 2021-04-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagenproducto',
            new_name='imagen',
        ),
    ]
